### ISSUE TITLE
don't skipt pushes with a=test-only as push with builds to ship

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-releng/scriptworker-scripts#139]
Added by https://github.com/mozilla-releng/scriptworker-scripts/pull/79/commits/6d620a1f22d933e3c93653fb4d6cfe32113bcb0f

fe6f34b2859f got used for 73.0b7 and not e7f513315a2a https://treeherder.mozilla.org/#/jobs?repo=mozilla-beta&group_state=expanded&resultStatus=success%2Ctestfailed%2Cbusted%2Cexception%2Cusercancel%2Csuperseded%2Cretry&searchStr=build%2Caddon&fromchange=30f26136b45efd9bf04d1a4642df5d96875108bd&selectedJob=285504011

RyanVM, jcristau and I favor not skipping a=test-only pushes. They have the builds and tests.

**Comment by MihaiTabara** [comment]
CC: @Callek

**Comment by jcristau** [comment]
73.0b11 was not built automatically, presumably because https://treeherder.mozilla.org/#/jobs?repo=mozilla-beta&revision=c24dfbda267ec738479bdc63ac6cfad60212d8dc was skipped:

https://firefoxci.taskcluster-artifacts.net/Gd6epyJuQ06zSCCWSo3xUQ/0/public/logs/live_backing.log
