### ISSUE TITLE
[treescript] Make CLOBBER file reset optional

### ISSUE THREAD

**Issue by jfx2006** [mozilla-releng/scriptworker-scripts#181]
For Thunderbird purposes, the merge-automation work looks great and should cover everything that we currently do with scripts. 

The only thing I saw that will be problematic is the CLOBBER file update. I'm proposing adding a config field "clobber-file". When set look for that file and update, when set to false, skip it.

[Bug 1619767](https://bugzilla.mozilla.org/show_bug.cgi?id=1619767)

**Comment by escapewindow** [comment]
+1. Putting it in the config file, at the worker level, seems preferable over putting it into the task definition. We may want to specify which action the clobber file refers to, e.g. `merge_day_clobber_file`.

**Comment by jfx2006** [comment]
Fixed by #183
