### ISSUE TITLE
treescript - hardcoded version.txt file used for generating tag names

### ISSUE THREAD

**Issue by jfx2006** [mozilla-releng/scriptworker-scripts#206]
There's a few places in Treescript's merge-automation code that read browser/config/version.txt to create a tag name.
Thunderbird's version file is at comm/mail/config/version.txt.
I was thinking of doing something similar to 'merge_day_clobber_file', setting 'version_file' in the worker config.

**Comment by jcristau** [comment]
AIUI #207 was meant to fix this.  Closing.
