### ISSUE TITLE
fix docker tox

### ISSUE THREAD

**Issue by escapewindow** [mozilla-releng/scriptworker-scripts#236]
The problem is we use `requirements/local.txt` for both py37 and py38. We need to use the python-specific local requirements file.

This will probably be easiest if we put the PYTHON_VERSION in both filenames, so we can `RUN pip install -r requirements/local.$PYTHON_VERSION.txt` or similar in the Dockerfile.

**Comment by MihaiTabara** [comment]
@alopezz fixed this in https://github.com/mozilla-releng/scriptworker-scripts/pull/271, I think we can close this. Thank you for your help, Alex!
