### ISSUE TITLE
[treescript] kill dashboard_revision_info branch of l10n bumper code when esr68 dies

### ISSUE THREAD

**Issue by bhearsum** [mozilla-releng/scriptworker-scripts#255]
I think beta and esr68 will use this branch of code til a) central-> beta merge day, and b) we turn off the bumper in esr68. Once those happen, then yes, I'd love to clean this up.

_Originally posted by @escapewindow in https://github.com/mozilla-releng/scriptworker-scripts/pull/254#discussion_r474359285_

**Comment by escapewindow** [comment]
@jfx2006 is Thunderbird all caught up here? Firefox beta is using the new l10n-bumper behavior, and we turned off esr68 Fx l10n-bumper.

**Comment by jfx2006** [comment]
Yes, you should be able to proceed. Thunderbird beta is using the new behavior and we don't run the bumper anywhere else.
