### ISSUE TITLE
[addonscript] update AMO usage from v3 to v4

### ISSUE THREAD

**Issue by eviljeff** [mozilla-releng/scriptworker-scripts#316]
AMO is deprecating v3 of the AMO api (mozilla/addons#1805) and addonscript calls https://addons.mozilla.org/api/v3/addons/{id}/versions/{version}/ so it needs changing to /v4/.  There aren't any changes to the signing API that's used (that I'm aware of) so it should just be a matter of `v3` to `v4` in 3 places in https://github.com/mozilla-releng/scriptworker-scripts/blob/master/addonscript/src/addonscript/api.py

**Comment by escapewindow** [comment]
It looks like there isn't urgency in pushing this to production? I'll plan on pushing this out next week, post-85.0, unless that assumption is wrong.

**Comment by eviljeff** [comment]
> 
> 
> It looks like there isn't urgency in pushing this to production? I'll plan on pushing this out next week, post-85.0, unless that assumption is wrong.

The v3 api won't be removed until the end of 2021 (Firefox is still using it at the moment) so absolutely no urgency.
