### ISSUE TITLE
treescript's version bump appended "esr" to version.txt which should only be append in version_display.txt

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-releng/scriptworker-scripts#349]
Today treescript automatically bumped the version of mozilla-esr78 to 78.10.1esr https://hg.mozilla.org/releases/mozilla-esr78/rev/ebc0ee4b3262cfc54cbeb809e9ceee39c3f08966#l1.4

version.txt should have `78.10.1` and version_display.txt `78.10.1esr`.

```
it's probably worth noting that this might have been broken for awhile
since we normally do the major version bump on Monday and ship on Tuesday (so the automated bump is a no-op)
what I'm saying is that we generally don't exercise this code because we do a 78.X bump on Monday so the 78.X-1.1 bump on Tuesday doesn't happen
so this could have been broken for awhile without us noticing because the merge day version bump Just Works
```

**Comment by escapewindow** [comment]
ESR release-version-bump-firefox task: https://firefox-ci-tc.services.mozilla.com/tasks/eRJECV1fQx6wgNcBU600bw
The current logic in treescript doesn't seem to differentiate behaviors between the different version files.

**Comment by Archaeopteryx** [comment]
Yes, not seeing file-agnostic code handling the version bump in https://github.com/mozilla-releng/scriptworker-scripts/blob/a196a7a660a09de392e891d1fe0ea1c24e2381a8/treescript/src/treescript/versionmanip.py#L66-L161

**Comment by escapewindow** [comment]
The merge day version bump works properly. We may want to share the logic there for the release version bumps in beta and esr.

**Comment by jcristau** [comment]
Happened again here:
https://hg.mozilla.org/releases/mozilla-esr78/rev/50cd89d7a5fdc97c2101954cdf3044934b789a1f

**Comment by escapewindow** [comment]
Looks like the merge day task has

```
      "version_files": [
        {
          "filename": "config/milestone.txt",
          "new_suffix": ""
        },
        {
          "filename": "browser/config/version.txt",
          "new_suffix": ""
        },
        {
          "filename": "browser/config/version_display.txt",
          "new_suffix": "b1"
        }
      ],
      "fetch_version_from": "browser/config/version.txt"
```

for `treescript.merges.apply_rebranding`.

We may want to rewrite the `versionmanip` functions to follow a similar logic, update the esr bump task definition, and maybe call the `versionmanip` functions from the `treescript.merges.apply_rebranding` to avoid a duplication of logic.
