### ISSUE TITLE
port treescript to scriptworker-scripts

### ISSUE THREAD

**Issue by escapewindow** [mozilla-releng/scriptworker-scripts#5]
See [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1562902#c2).

1. [X] import treescript into scriptworker-scripts, except in a subdir. [This](https://stackoverflow.com/a/42238385) may be a way to do so while preserving history. (Note: use `git merge --allow-unrelated-histories <branch>`)
2. [X] update the various helper files (e.g. tox.ini or .taskcluster.yml when we have it) to know about iscript, and standardize how we release etc.
3. [X] (non-blocker) replace `scriptworker.*` imports with `scriptworker_client` imports. This may involve adding more functionality to `scriptworker_client`. This does involve moving away from using `context` objects and using more functional functions.
4. [X] (non-blocker) ideally we have google docstrings for every function
5. (non-blocker) possibly add:

    - [X] push_loop functionality
    - [X] rebasing - via push loop
    - [X] relbranch support
    - [ ] sparse profile support
    - [ ] git support

    If not, let's file feature tracking issues for them. (This may involve copying issues from treescript over to scriptworker-scripts)

6. [X] (non-blocker) l10n-bumper support? This will involve calling cron hooks via cron.yml to trigger the tasks. Make sure we have [esr68 fennec support](https://bugzilla.mozilla.org/show_bug.cgi?id=1562902#c2)
7. [ ] dockerfiles and testing
8. [ ] GCP deployment story
9. [ ] Deploy, quarantine old treescript workers
10. [ ] Kill old treescript workers once we're fully deployed and working

**Comment by escapewindow** [comment]
[wip](https://github.com/escapewindow/scriptworker-scripts/commits/treescript):

- imported history
- moved to treescript/
- moved to a src/treescript/ + tests/ layout
- mypy and black

Currently:
- [X] fixing up tests
- [X] merging in treescript 1.2.1

**Comment by escapewindow** [comment]
Re: `merge day support? This does mean that treescript will have greater hg.m.o perms than just version bumping needs.`: Simon's signed up to do the merge day automation; we may leave this part for later.

**Comment by tomprince** [comment]
The keys we have on the mergeday instances are quite restricted by hg.m.o hooks. In some ways, using those would be *more* restrictive than than the current treescript user. (We should think about restrict that user as well, in the future)

**Comment by escapewindow** [comment]
Nice, so if we either have both sets of creds, or a set of creds with combined privs, we should be good for merge day.

**Comment by escapewindow** [comment]
L10n bumping works. I need test coverage + testing on Try.

**Comment by escapewindow** [comment]
Merged! We still need docker support + automation and potential in-tree fixes before we can retire the mozilla-releng/treescript repo.

**Comment by escapewindow** [comment]
We're fixing up, but essentially done.
