### ISSUE TITLE
Migrate Balrog submission to Python 3

### ISSUE THREAD

**Issue by bhearsum** [mozilla-releng/scriptworker-scripts#50]
As far as I know, we're still running the Balrog submission scripts with Python 2.7. We should it upgrade it to 3.7 or 3.8.

**Comment by MihaiTabara** [comment]
I think we've already switched to py3 within https://github.com/mozilla-releng/balrogscript/commit/fe4b2d858beac72b716092bfa3605819ed45f358 and released with `6.0.0`.

**Comment by bhearsum** [comment]
Oh cool! I didn't realize.
