### ISSUE TITLE
iscript: improve parallelization by using a cross-process lockfile for notarization

### ISSUE THREAD

**Issue by escapewindow** [mozilla-releng/scriptworker-scripts#6]
<s>In this case,

task1:
    - sign widevine
    - sign omnija
    - sign mac
    - upload to notarization
    - upload artifacts, with a manifest file showing the UUID

task 2:
    - download the app(s) and manifest(s) from task 1
    - poll apple for completed notarization
    - staple
    - pkg creation+signing
    - upload notarized app(s) + pkg(s)

beetmover would download from task 2. Task 2 would allow us to poll apple for longer than max polling timeout, by rerunning just task 2.

This would require in-tree changes as well.

Maybe mac_notarize_phase1 and mac_notarize_phase2 behaviors?</s>

We're moving forward with the plan in [this comment](https://github.com/mozilla-releng/scriptworker-scripts/issues/6#issuecomment-517471142).

**Comment by escapewindow** [comment]
Previously, we were concerned / daunted with the idea of changing all the downstream deps to download from a different kind than build-signing (or nightly-l10n-signing or release-{partner-repack,eme-free}-signing).

Potential workaround:

```
aki [15:24]
i wonder if i could do something like build -> pre-signing -> build-signing, just to avoid changing downstream deps

(everything still downloads from build-signing, but build-signing has an optional additional dep)

nthomas [15:25]
that sounds good for notarization, would we only use if it for that ?

aki [15:25]
i think so. so it would only be for mac, if we're notarizing. otherwise just create the build-signing task
and we'd repeat for nightly-l10n-signing and release-{eme-free,partner-repack}-signing
```

**Comment by tomprince** [comment]
If it makes sense, I don't think we should make the scriptworker more complicated to avoid needing to change the taskgraph.

**Comment by escapewindow** [comment]
I don’t think this makes the scriptworker more complicated at all. It makes the beetmover repackage changes less ugly.

**Comment by escapewindow** [comment]
Catlee was proposing *three* tasks.

1. sign and submit for notarization; upload signed tarballs and notarization UUIDs as artifacts
2. download the notarization UUIDs and poll Apple
3. download the signed tarballs, staple the notarization, and build/sign the pkg

The idea was (2) should be super small and lightweight, so we could run a lot of these workers, or run a service like BBB that can perform meta-actions on the queue. (The idea of purposely running retries of the 2nd task in [the original comment](https://github.com/mozilla-releng/scriptworker-scripts/issues/6#issue-464381056) isn't Catlee's favorite.)

Currently polling requires both XCode and the notarization creds, so we probably won't run these on general workers. I proposed that if we have this 3-step notarization, that we add support in scriptworker for claiming `n` tasks, and run them each in their on `work_dir` concurrently. We could have `n` of these workers on each mac. If they're only polling Apple, this should be ok.

We could also potentially play with the idea of running steps 2 and 3 in these more lightweight workers, and bring it back down to 2 tasks.

**Comment by escapewindow** [comment]
Callek proposed a single task, that exits early and attempts to pick up from the previous run:

1. sign and submit for notarization; upload signed tarballs and a manifest of notarization UUIDs and last successful action as artifacts; exit early and schedule a rerun
2. download those and attempt to pick up from where we left off from the previous run. If we hit a timeout or an error, exit early and upload a new manifest of UUIDs and status, exit early and schedule a rerun; repeat step 2
3. if we hit an error where we need to re-submit for notarization, we can note that in the manifest and start again from signing and re-submitting.
4. if we finish successfully, upload the signed-and-notarized app and pkg, and go green.

This has the same property of lots of intentional blues that we were potentially trying to avoid with the 3-task solution, but has the nice property of letting us start over if we detect issues with the notarization submission down the line. With the 2 or 3 task solution, if the first task goes green and we notice we need to re-submit in the 2nd or 3rd task, we're faced with a human having to rerun a previously green task.

**Comment by escapewindow** [comment]
Ben proposed claiming multiple tasks on a single host, and using a shared semaphore to limit concurrency around notarization. (I like this idea a lot.) Breaking this down:

## Multiple tasks on a single host

- We can run multiple scriptworker daemons, as proven by the dep notarization pool, which run 2 fx dep scriptworkers and 1 tb dep scriptworker apiece. The dep pool doesn't notarize, so they don't need semaphores around notarization. Each scriptworker daemon runs in its own user account, so we don't have to worry about user-level XCode locks.

- Alternately, we can have scriptworker claim multiple tasks, and be able to run them concurrently in separate `work_dir`s. (We mentioned this [above](https://github.com/mozilla-releng/scriptworker-scripts/issues/6#issuecomment-516615661).) We then have to deal with non-notarization XCode locks, by either a) running each script as a different user, or b) wrapping all XCode calls in iscript with `sudo`.

## a shared semaphore around notarization

Each task is run in a separate python process, essentially its own `python iscript config_file`, so they can't have a shared python semaphore. We settled on `lockfile` to use file-based locking, but `lockfile` doesn't come standard on osx, and we can't use homebrew. We can look at [`fcntl.lockf`](https://docs.python.org/3/library/fcntl.html#fcntl.lockf) to use file-based locking in python.

We want to:
    1. have a lockfile per notary user
    2. claim a lockfile before using that notary user
    3. clean up the lockfile after we're done, including exceptions

In addition, we should probably do some combination of cleaning up lockfiles on scriptworker start, and monitoring for stale lockfiles in nagios.

There's also XCode's lockfile, which could work in lieu of a separate lockfile. However, this may add more noise to the error messages when we try to use a notary account that's currently in use.

**Comment by escapewindow** [comment]
> We can look at [`fcntl.lockf`](https://docs.python.org/3/library/fcntl.html#fcntl.lockf) to use file-based locking in python.

`os.open` provides this functionality on OSX:

```python
#!/usr/bin/env python
from __future__ import print_function

import os
import time

success = False
fd = None
while not success:
    try:
        fd = os.open("/tmp/foo", os.O_EXLOCK|os.O_RDWR|os.O_CREAT|os.O_EXCL)
        t = time.time()
        os.write(fd, str(t).encode("utf-8"))
        print(f"Got it at {t}")
        success = True
        time.sleep(300)
    except FileExistsError:
        print("Locked; sleeping 10 before trying again")
        time.sleep(10)
    finally:
        if fd is not None:
            os.close(fd)
            os.remove("/tmp/foo")

print("Exiting")
```

We'd want to do something like this, but with a pool of lockfiles, one lockfile per notary account. Randomize that list, go through them trying to acquire a lock. If we get a lock, use that notary account. If not, sleep and try again.

Using [fasteners](https://pypi.org/project/fasteners/):

```python
#!/usr/bin/env python
from __future__ import print_function

from contextlib import contextmanager
import fasteners
import os
import time


@contextmanager
def lockfile(paths, attempts=5, sleep=5):
    for attempt in range(0, attempts):
        for path in paths:
            lock = fasteners.InterProcessLock(path)
            locked = lock.acquire(blocking=False)
            if locked:
                try:
                    print("lock at {}".format(path))
                    yield path
                    return
                finally:
                    os.remove(path)  # need this to not error out if gone
                    lock.release()
        print("Couldn't get lock; sleeping {}".format(sleep))
        time.sleep(sleep)
    raise Exception("Can't get lock")

with lockfile(["/tmp/foo1", "/tmp/foo2"]):
    time.sleep(300)

print("Exiting")
```

If we make this fasteners example an async contextmanager, we could use it as a semaphore to use with `semaphore_wrapper`.

**Comment by escapewindow** [comment]
I put this on hold a while back. The notarization bustages over the previous weekend made it clear that we probably need a 3-task solution instead. Closing in favor of #55 .
