### ISSUE TITLE
add ability in shipitscript to create a beta release

### ISSUE THREAD

**Issue by lundjordan** [mozilla-releng/scriptworker-scripts#71]
this is about essentially adding functionality for shipitscript to be able to:

POST https://shipit-api.mozilla-releng.net/releases

via https://github.com/mozilla-releng/shipit/blob/master/api/src/shipit_api/api.yml#L44

**Comment by rail** [comment]
The hardest part would be passing all the parameters, especially partials. I actually wanted to add another API endpoint for partial suggestion, so we don't need to implement this logic in multiple places (UI, shipitscript). Or maybe have a parameter to tell shipit to "make it so" for partials :)

**Comment by rail** [comment]
The "make it so" feature is ready now. "partial_updates" should be set to "auto". This payload should just work:
```json
{
  "product": "firefox",
  "branch":"releases/mozilla-beta",
  "revision": "e9247c9a40c85fab688cd52ca0c82192a18eb2e4",
  "version": "72.0b4",
  "build_number": 6,
  "partial_updates": "auto"
}
```

One thing that we need to calculate is the build number, which should be `$last_build_number + 1`. The last build number can be fetched from shipit. Something like this:

```python
url = f"{SHIPIT_API}/releases"
params = {
    "product": product,
    "version": version,
    "branch": branch,
    "status": "shipped,aborted,scheduled",
}
req = requests.get(url, params=params)
build_numbers = [r["build_number"] for r in req.json()]
max_build_number = max(build_numbers) or 0
our_build_number = max_build_number +1
```

I hope it helps.

**Comment by MihaiTabara** [comment]
Work mentioned here is tracked in https://github.com/mozilla-releng/scriptworker-scripts/pull/93

**Comment by MihaiTabara** [comment]
Done in the aformentioned PR.
