### ISSUE TITLE
add ability in shipitscript to trigger a phase

### ISSUE THREAD

**Issue by lundjordan** [mozilla-releng/scriptworker-scripts#72]
this is about essentially adding functionality for shipitscript to be able to:

POST https://shipit-api.mozilla-releng.net/releases/{name}/{phase}

via https://github.com/mozilla-releng/shipit/blob/master/api/src/shipit_api/api.yml#L165

**Comment by rail** [comment]
This should be super easy, just use PUT instead of POST with no body. We'll just need to change the endpoint to accept Tascluster auth (right now it's Auth0 only). Should be easy, we already have some endpoint using it. Just need to change the logic to accept both auth types.

**Comment by MihaiTabara** [comment]
This is tracked in https://github.com/mozilla-releng/scriptworker-scripts/pull/93

**Comment by MihaiTabara** [comment]
Done in the aformentioned PR.
