### ISSUE TITLE
impl shipitscript method that determines most recent shipped rev

### ISSUE THREAD

**Issue by lundjordan** [mozilla-releng/scriptworker-scripts#74]
I suppose this will poll product-details? Most recent release in shipit with triggered ship phase?

It's needed to contrast against the treescript task that will check for the most recent "[good rev](https://github.com/mozilla-releng/scriptworker-scripts/issues/73)" to ship from, If the most recent good rev in a repo is newer than the most recent shipped rev, we are good to create a new release based off of it.

**Comment by tomprince** [comment]
I don't think this logic belongs in a scriptworker, it should be in the action task that is triggered by cron direcly. This only needs read-only access to shipit, so does not need to be protected by chain-of-trust.

There is the issue that the shipit api is behind the VPN, but we should address that by making a read-only version available outside the vpn.

**Comment by MihaiTabara** [comment]
This is tracked in https://github.com/mozilla-releng/scriptworker-scripts/pull/93

**Comment by MihaiTabara** [comment]
Done in the aformentioned PR.
