### ISSUE TITLE
Update to follow Best Practices

### ISSUE THREAD

**Issue by escapewindow** [mozilla-releng/scriptworker-scripts#8]
- [ ] Use Docker & Docker Compose for running a local dev environment, based on the python:3 image
- [ ] Use pip-compile-multi, and Pyup.io for dependency management
  - See https://github.com/mozilla-releng/releng-rfcs/blob/master/rfcs/0022-app-best-practices.md#dependency-management for requirements file details.
- [X] Use tox as a test runner
- [x] Use Taskcluster for CI
- [ ] Ensure production pushes happen manually, in response to bugs filed
- [ ] Ensure stage pushes happen in response to balrog_stage tags on Dockerhub
- [ ] Eliminate the development environment, if it exists

(Remove items that are not applicable to this project).

**Comment by escapewindow** [comment]
@mozbhearsum are we done here?

**Comment by bhearsum** [comment]
Yes!
